Create 04-everyday-shell.md
barraponto/usegit pull request #11
Opened 2023-08-23 14:01 UTC by GrayR0ot

Added a comprehensive Russian translation for the 'Everyday Shell' lesson, enhancing accessibility for Russian-speaking users and improving the project's global reach. Your contribution is greatly appreciated

2023-08-23 14:01 UTC, GrayR0ot commented
@barraponto Request for review

2023-08-23 14:19 UTC, barraponto commented
@GrayR0ot do you know any russian-speaking person who can come here and review the translation?
Izvinite, ya ne vladeju russkim...

2023-08-23 14:20 UTC, barraponto requested changes

2023-08-23 14:20 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +---
Also, I'm pretty sure the keywords must stay in english for slidev to correctly interpret them.
The values can be in Russian, though.

2023-08-23 14:48 UTC, amniriane commented on translations/ru/04-everyday-shell.md
> +---
it's ok

2023-08-23 15:01 UTC, barraponto requested changes

2023-08-23 15:01 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +---
I mean, in lines like `Заголовок: Повседневная оболочка`, `Заголовок` must be `title` for the software to interpret it correctly. The value can stay in Russian, although some values are actually identifiers, like `default`, `slide-left` and `statement`

2023-08-23 19:32 UTC, GrayR0ot commented
fixed header values matching source

2023-08-24 09:05 UTC, barraponto requested changes

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +theme: по умолчанию
```suggestion
theme: default
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-08-24 09:05 UTC, barraponto commented on translations/ru/04-everyday-shell.md
> +макет: вступление
```suggestion
layout: intro
```

2023-09-11 16:42 UTC, closed without merging